import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#e1fdff',
        'primary-container': '#00f2ff',
        'on-primary': '#00363a',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'on-primary-container': '#006a71',
        'primary-fixed': '#74f5ff',
        'primary-fixed-dim': '#00dbe7',
        secondary: '#adc6ff',
        'secondary-container': '#0067d7',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary': '#002e68',
        'on-secondary-container': '#e6ecff',
        'on-secondary-fixed': '#001a41',
        'on-secondary-fixed-variant': '#004493',
        tertiary: '#f4f8ff',
        'tertiary-container': '#d3dce7',
        'tertiary-fixed': '#dae3ef',
        'tertiary-fixed-dim': '#bec7d2',
        'on-tertiary': '#29313a',
        'on-tertiary-container': '#58616a',
        'on-tertiary-fixed': '#141c25',
        'on-tertiary-fixed-variant': '#3f4851',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-tint': '#00dbe7',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#b9cacb',
        background: '#131313',
        'on-background': '#e5e2e1',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        outline: '#849495',
        'outline-variant': '#3a494b',
        'inverse-primary': '#00696f',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"JetBrains Mono"', 'monospace'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
    },
  },
  plugins: [],
} satisfies Config;
